name: PRINT ORDER RECEPTION SERVICE TEST Report

on:
  push:
    branches:
      - main
      - hotfix/**
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PYTHONUNBUFFERED: 1
      ENVIRONMENT: test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create temporary .env
        run: |
          echo "APP_PORT=3001" >> .env
          echo "MONGO_HOST=mongodb://localhost:27017/ms-print-orders-test" >> .env
          echo "TEST_MONGO_HOST=mongodb://localhost:27017/ms-print-orders-test" >> .env
          echo "APP_JWT_SECRET=testsecret_github_actions" >> .env
          echo "SENTRY_DSN='https://examplePublicKey@o0.ingest.sentry.io/0'" >> .env


      - name: Run tests with coverage
        run: |
          mkdir -p reports
          pytest --junitxml=reports/pytest.xml --cov=app --cov-report=xml --cov-report=term

      - name: Pytest Coverage & Test Report
        if: github.event_name == 'pull_request'
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./coverage.xml
          junitxml-path: ./reports/pytest.xml
          coverage-title: 🧪 Testing Coverage
          coverage-path-prefix: "app/"